"""
Chatbot Views (NL to SQL)
Open SQL Programming:
- Accept natural language questions
- Use an LLM to generate SQL
- Execute the SQL against the MySQL database
- Return the results as JSON
"""

from django.db import connection
from rest_framework.decorators import api_view
from rest_framework.response import Response
from openai import OpenAI
import os

# 延迟初始化OpenAI客户端
def get_openai_client():
    api_key = os.getenv('OPENAI_API_KEY')
    if not api_key:
        raise ValueError("OPENAI_API_KEY environment variable is not set")
    return OpenAI(api_key=api_key)

SCHEMA_DESCRIPTION = """
You are an assistant that writes MySQL SELECT queries for the database `sql_study_room`.

The available tables and columns are:

USER_PROFILE(
    Email VARCHAR(100) PRIMARY KEY,
    First_name VARCHAR(50),
    Last_name VARCHAR(50)
);

ACCOUNT(
    Account_number INT PRIMARY KEY,
    Email VARCHAR(100),
    Register_date DATE,
    Student_flag BOOLEAN,
    Admin_flag BOOLEAN
    -- Email references USER_PROFILE(Email)
);

DIFFICULTY_TAG(
    Difficulty_ID INT PRIMARY KEY,
    Difficulty_level ENUM('EASY','MEDIUM','HARD')
);

CONCEPT_TAG(
    Concept_ID INT PRIMARY KEY,
    SQL_concept VARCHAR(50)
);

TAG(
    Tag_ID INT PRIMARY KEY,
    Difficulty_ID INT,
    Concept_ID INT
    -- Difficulty_ID references DIFFICULTY_TAG(Difficulty_ID)
    -- Concept_ID references CONCEPT_TAG(Concept_ID)
);

PROBLEM(
    Problem_ID INT PRIMARY KEY,
    Tag_ID INT,
    Problem_description VARCHAR(1000),
    Review_status BOOLEAN,
    Solution_ID INT
    -- Tag_ID references TAG(Tag_ID)
);

SUBMISSION(
    Submission_ID INT PRIMARY KEY,
    Problem_ID INT,
    Account_number INT,
    Submission_description VARCHAR(1000),
    Is_correct BOOLEAN,
    Time_start DATETIME,
    Time_end DATETIME
    -- Problem_ID references PROBLEM(Problem_ID)
    -- Account_number references ACCOUNT(Account_number)
);

ATTEMPT(
    Attempt_ID INT PRIMARY KEY,
    Problem_ID INT,
    Account_number INT,
    Attempt_number INT,
    Is_submitted BOOLEAN,
    Submission_ID INT
    -- Problem_ID references PROBLEM(Problem_ID)
    -- Account_number references ACCOUNT(Account_number)
);

Rules:
- You must ONLY generate a single MySQL SELECT query.
- Do NOT use INSERT, UPDATE, DELETE, DROP, CREATE, or ALTER.
- Use only the tables and columns listed above.
- Prefer explicit JOINs instead of subqueries when possible.
- If the user question is ambiguous, make a reasonable assumption and still produce a SELECT query.
"""


def call_llm_for_sql(question: str) -> str:
    """
    Call the OpenAI API to convert a natural language question into a SQL query.
    Returns the SQL string only.
    """
    prompt = f"""
{SCHEMA_DESCRIPTION}

User question:
\"\"\"{question}\"\"\"

Write ONE MySQL SELECT query that answers the question.
Output only the SQL statement, without explanation or backticks.
"""

    client = get_openai_client()
    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[
            {
                "role": "system",
                "content": "You are a helpful assistant that writes safe MySQL SELECT queries."
            },
            {"role": "user", "content": prompt},
        ],
        temperature=0,
    )

    sql = response.choices[0].message.content.strip()
    return sql


def execute_sql(sql: str):
    """
    Execute the generated SQL and return results as:
    (columns, rows_as_dict_list)

    A simple safety check is enforced: only SELECT statements are allowed.
    """
    if not sql:
        raise ValueError("Empty SQL generated by LLM.")

    stripped = sql.strip().lower()
    if not stripped.startswith("select"):
        raise ValueError("Only SELECT statements are allowed.")

    with connection.cursor() as cursor:
        cursor.execute(sql)
        columns = [col[0] for col in cursor.description]
        rows = cursor.fetchall()
        results = [dict(zip(columns, row)) for row in rows]

    return columns, results


@api_view(["POST"])
def nl2sql(request):
    """
    Open SQL Programming entrypoint.

    URL:
        POST /nl2sql/

    Request body (JSON):
        {
            "question": "Show me how many problems are solved in this semester"
        }

    Response (JSON):
        {
            "question": "...",
            "sql": "...",
            "columns": [...],
            "rows": [ {col: value, ...}, ... ]
        }
    """
    question = request.data.get("question", "").strip()

    if not question:
        return Response({"error": "field 'question' is required"}, status=400)

    # 1. Ask the LLM to generate SQL
    try:
        generated_sql = call_llm_for_sql(question)
    except Exception as e:
        return Response(
            {
                "error": "LLM error",
                "detail": str(e),
            },
            status=500,
        )

    # 2. Execute the generated SQL
    try:
        columns, rows = execute_sql(generated_sql)
    except Exception as e:
        return Response(
            {
                "error": "SQL execution error",
                "sql": generated_sql,
                "detail": str(e),
            },
            status=400,
        )

    # 3. Return the SQL and the query results
    return Response(
        {
            "question": question,
            "sql": generated_sql,
            "columns": columns,
            "rows": rows,
        }
    )
